grafana:
  service:
    type: LoadBalancer

prometheus:
  service:
    type: LoadBalancer

alertmanager:
  service:
    type: LoadBalancer

windowsMonitoring:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
thanosRuler: 
  enabled: false