apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: exempt-system-namespaces
  namespace: kyverno
spec:
  exceptions:
    - policyName: require-signed-images
      ruleNames:
        - verify-jenkins-signature
    - policyName: require-sbom-attestation
      ruleNames:
        - verify-sbom-attestation
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system
            - kyverno
