apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-sbom-attestation
spec:
  validationFailureAction: Audit
  background: true
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-sbom-attestation
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - argocd
                - monitoring
      verifyImages:
        - imageReferences:
            - "docker.io/chahatyadav1/dashboard*"
          required: true
          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEe7NWS9kmWL+VgZ/fjiLLuou7Rp0C
                      3B0D3BPzygjX6tQosAqt3s/LpZyiumJEuuKiJqNNLWrXjPrq03kp5ISIow==
                      -----END PUBLIC KEY-----
                    rekor:
                      ignoreTlog: true
                      url: https://rekor.sigstore.dev
          attestations:
            - predicateType: https://spdx.dev/Document
              conditions:
                - all:
                    - key: "{{ spdxVersion }}"
                      operator: Equals
                      value: "SPDX-2.3"
